Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_main_menu.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor1_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor1_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_monsters_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_monsters_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_skills_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_skills_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_shared_machines_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_shared_machines_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_shared_doors.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_shared_elevators.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_message_speed.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor3.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_prebattle.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_battle_menu.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_battle_quotes.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_battle_text.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_battle_menu_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_battle_menu_3.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_battle_menu_4.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_battle_data.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom3.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw3_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw3_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor4.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_type_names.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_tsuyosa.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_opening.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_pause.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_submenu.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom4.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw4_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw4_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw4_3.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor5.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom5.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw5_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw5_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw5_3.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_mw5_g.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom5_epilogue.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_ngplus_dialog.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor1_postgame.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom1_postgame.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor2_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom2_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor3_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom3_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor4_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom4_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floor5_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_darkroom5_pg.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_floorbf1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_link.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_link_duel.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_ed_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_op_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_op_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_op_3.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_op_4.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_credits.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_attract_1.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_attract_2.txt
Atlas.exe "Yu-Gi-Oh! Monster Capsule GB eng font.gbc" scripts\script_attract_3.txt